FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.mod ./
# COPY go.sum ./  # если есть
RUN go mod download
## add comment
COPY main.go ./
RUN CGO_ENABLED=0 go build -o api .
FROM scratch
COPY --from=builder /build/api /api
EXPOSE 8080
ENTRYPOINT ["/api"]
